# Makefile para el servidor de autenticacion.

all: main

# Genera los archivos compilados para el servidor y sus dependencias
main: 
		javac a_rmifs.java

# Corre el servidor, utilizar con los argumentos adecuados
run:
		java a_rmifs

# Elimina los archivos generados
clean:
		rm -f *.class
