# Makefile para el cliente

all: main

# Compila el cliente y sus dependencias
main: 
		javac c_rmifs.java

# Corre el cliente, utilizar con los argumentos necesarios
run:
		java c_rmifs

# Elimina los archivos generados 
clean:
		rm -f *.class
