# Makefile para el servidor de archivos
all: main

# Genera los archivos compilados para el servidor y sus dependencias
main: 
		javac s_rmifs.java

# Corre el servidor de archivos, utilizar con los argumentos necesarios
run:
		java s_rmifs

# Elimina los archivos generados
clean:
		rm -f *.class
